-- spec-16: task sets.
--
-- HAND-EDITED (DECISIONS 2026-08-26). Prisma re-proposes, on EVERY migration, drops of the two
-- pgvector HNSW indexes and of the generated-column defaults on MasterItem.searchText and
-- KbChunk.textSearch, because it cannot model either. Applying them would destroy the knowledge
-- base's vector search and the admin question search. They are removed below and must be removed
-- again next time. Do NOT edit this file after it has been applied — that changes its checksum and
-- every later `migrate dev` then demands a full database reset.

-- CreateEnum
CREATE TYPE "TaskSetStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED');

-- AlterEnum
ALTER TYPE "AttemptMode" ADD VALUE 'TASK_SET';

-- AlterTable
ALTER TABLE "ExamAttempt" ADD COLUMN     "taskSetId" TEXT;

-- CreateTable
CREATE TABLE "TaskSet" (
    "id" TEXT NOT NULL,
    "number" INTEGER NOT NULL,
    "licenseClassId" TEXT NOT NULL,
    "status" "TaskSetStatus" NOT NULL DEFAULT 'DRAFT',
    "poolSize" INTEGER NOT NULL,
    "paperSize" INTEGER NOT NULL,
    "passMark" INTEGER NOT NULL,
    "timeLimitSec" INTEGER NOT NULL,
    "composition" JSONB NOT NULL,
    "buildId" TEXT,
    "publishedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TaskSet_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TaskSetMember" (
    "masterItemId" TEXT NOT NULL,
    "taskSetId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TaskSetMember_pkey" PRIMARY KEY ("masterItemId")
);

-- CreateTable
CREATE TABLE "TaskSetBuild" (
    "id" TEXT NOT NULL,
    "status" "BatchStatus" NOT NULL DEFAULT 'PENDING',
    "providerId" TEXT,
    "modelVersion" TEXT,
    "promptVersion" TEXT,
    "stats" JSONB NOT NULL,
    "warnings" JSONB NOT NULL,
    "requestedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TaskSetBuild_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TaskSetProgress" (
    "userId" TEXT NOT NULL,
    "taskSetId" TEXT NOT NULL,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "bestCorrect" INTEGER,
    "bestOutOf" INTEGER,
    "passedAt" TIMESTAMP(3),
    "lastAttemptId" TEXT,
    "lastAttemptAt" TIMESTAMP(3),
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TaskSetProgress_pkey" PRIMARY KEY ("userId","taskSetId")
);

-- CreateIndex
CREATE INDEX "TaskSet_licenseClassId_status_number_idx" ON "TaskSet"("licenseClassId", "status", "number");

-- CreateIndex
CREATE UNIQUE INDEX "TaskSet_licenseClassId_number_key" ON "TaskSet"("licenseClassId", "number");

-- CreateIndex
CREATE INDEX "TaskSetMember_taskSetId_idx" ON "TaskSetMember"("taskSetId");

-- CreateIndex
CREATE INDEX "TaskSetBuild_status_createdAt_idx" ON "TaskSetBuild"("status", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "TaskSetProgress_userId_idx" ON "TaskSetProgress"("userId");

-- CreateIndex
CREATE INDEX "ExamAttempt_taskSetId_userId_idx" ON "ExamAttempt"("taskSetId", "userId");

-- AddForeignKey
ALTER TABLE "ExamAttempt" ADD CONSTRAINT "ExamAttempt_taskSetId_fkey" FOREIGN KEY ("taskSetId") REFERENCES "TaskSet"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TaskSet" ADD CONSTRAINT "TaskSet_licenseClassId_fkey" FOREIGN KEY ("licenseClassId") REFERENCES "LicenseClass"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TaskSet" ADD CONSTRAINT "TaskSet_buildId_fkey" FOREIGN KEY ("buildId") REFERENCES "TaskSetBuild"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TaskSetMember" ADD CONSTRAINT "TaskSetMember_masterItemId_fkey" FOREIGN KEY ("masterItemId") REFERENCES "MasterItem"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TaskSetMember" ADD CONSTRAINT "TaskSetMember_taskSetId_fkey" FOREIGN KEY ("taskSetId") REFERENCES "TaskSet"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TaskSetBuild" ADD CONSTRAINT "TaskSetBuild_requestedById_fkey" FOREIGN KEY ("requestedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TaskSetProgress" ADD CONSTRAINT "TaskSetProgress_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TaskSetProgress" ADD CONSTRAINT "TaskSetProgress_taskSetId_fkey" FOREIGN KEY ("taskSetId") REFERENCES "TaskSet"("id") ON DELETE CASCADE ON UPDATE CASCADE;
